package utilities;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Properties;

import org.json.JSONArray;
import org.json.JSONObject;

public class ModelStructureTrimmer {

	//remove all nodes in model that have the tool name but  are not a part of the toolFindings
	public static void main(String[] args) {
		String[] toolFindings = "CWE-Unknown-Other CWE-216 CWE-399 CWE-316 CWE-704 CWE-191 CWE-436 CWE-80 CWE-476 CWE-364 CWE-59 CWE-78 CWE-270 CWE-294 CWE-252 CWE-407 CWE-307 CWE-775 CWE-334 CWE-112 CWE-470 CWE-299 CWE-319 CWE-1188 CWE-21 CWE-552 CWE-350 CWE-603 CWE-347 CWE-342 CWE-273 CWE-264 CWE-1 CWE-271 CWE-769 CWE-378 CWE-415 CWE-288 CWE-611 CWE-310 CWE-114 CWE-664 CWE-617 CWE-88 CWE-670 CWE-116 CWE-352 CWE-134 CWE-573 CWE-305 CWE-674 CWE-763 CWE-331 CWE-444 CWE-895 CWE-281 CWE-346 CWE-280 CWE-770 CWE-185 CWE-74 CWE-1286 CWE-259 CWE-17 CWE-118 CWE-371 CWE-248 CWE-918 CWE-89 CWE-369 CWE-668 CWE-323 CWE-384 CWE-917 CWE-36 CWE-1236 CWE-23 CWE-789 CWE-64 CWE-1076 CWE-400 CWE-269 CWE-787 CWE-829 CWE-20 CWE-388 CWE-183 CWE-228 CWE-256 CWE-208 CWE-532 CWE-610 CWE-417 CWE-943 CWE-255 CWE-916 CWE-119 CWE-123 CWE-178 CWE-441 CWE-667 CWE-915 CWE-367 CWE-760 CWE-312 CWE-93 CWE-297 CWE-279 CWE-202 CWE-680 CWE-788 CWE-644 CWE-472 CWE-345 CWE-405 CWE-538 CWE-335 CWE-203 CWE-798 CWE-489 CWE-639 CWE-261 CWE-459 CWE-275 CWE-406 CWE-99 CWE-749 CWE-87 CWE-707 CWE-199 CWE-313 CWE-527 CWE-353 CWE-349 CWE-642 CWE-193 CWE-669 CWE-672 CWE-754 CWE-697 CWE-131 CWE-120 CWE-426 CWE-522 CWE-778 CWE-434 CWE-823 CWE-640 CWE-300 CWE-540 CWE-494 CWE-567 CWE-22 CWE-303 CWE-361 CWE-507 CWE-909 CWE-497 CWE-125 CWE-209 CWE-73 CWE-565 CWE-834 CWE-327 CWE-862 CWE-306 CWE-190 CWE-665 CWE-757 CWE-126 CWE-122 CWE-254 CWE-285 CWE-117 CWE-427 CWE-682 CWE-428 CWE-1021 CWE-200 CWE-170 CWE-212 CWE-706 CWE-732 CWE-922 CWE-774 CWE-320 CWE-18 CWE-920 CWE-506 CWE-759 CWE-19 CWE-772 CWE-184 CWE-130 CWE-539 CWE-776 CWE-201 CWE-502 CWE-172 CWE-401 CWE-77 CWE-266 CWE-61 CWE-338 CWE-521 CWE-913 CWE-863 CWE-311 CWE-1187 CWE-601 CWE-838 CWE-287 CWE-332 CWE-35 CWE-358 CWE-317 CWE-302 CWE-189 CWE-693 CWE-843 CWE-79 CWE-321 CWE-115 CWE-435 CWE-113 CWE-662 CWE-924 CWE-912 CWE-362 CWE-98 CWE-824 CWE-684 CWE-276 CWE-681 CWE-240 CWE-90 CWE-416 CWE-377 CWE-91 CWE-290 CWE-835 CWE-379 CWE-16 CWE-471 CWE-822 CWE-295 CWE-425 CWE-250 CWE-284 CWE-326 CWE-613 CWE-404 CWE-805 CWE-129 CWE-755 CWE-121 CWE-534 CWE-457 CWE-385 CWE-908 CWE-330 CWE-354 CWE-94".split(" ");
        String structure = "      \"Category CWE-1228\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-676 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CWE-782 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-749 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1210\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-117 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-532 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-778 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1211\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-288 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-290 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-294 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-295 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-299 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-303 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-305 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-306 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-307 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-603 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-645 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-836 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1212\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-425 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-639 Measure\" : { },\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1006\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-560 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-489 Measure\" : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-547 Measure\" : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE           : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-627 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-628 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-694 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1041 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1043 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1044 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1045 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1046 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1048 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1049 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1050 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1063 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1065 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1066 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1067 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1070 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1071 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1072 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1073 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1079 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1082 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1084 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1085 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1087 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1089 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1091 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1092 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1094 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1097 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1098 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1099 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1101 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1102 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1103 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1104 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1106 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1107 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1108 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1109 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1113 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1114 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1115 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1116 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1117 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1126 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1127 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1235 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-438\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-438 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-115 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-179 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-408 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-437 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-439 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-440 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-444 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-480 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-483 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-484 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-551 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-698 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-733 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-783 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-835 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-837 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-841 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1025 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1037 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-840\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-840 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-283 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-288 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-639 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-640 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-708 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-770 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-826 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-837 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-841 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-417\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-417 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-346 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-385 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-419 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-420 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-425 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-515 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-924 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-940 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-941 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1226\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1043 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1047 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1055 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1056 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1060 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1064 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1074 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1075 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1080 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1086 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1095 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1119 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1121 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1122 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1123 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1124 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1125 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-557\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-367 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-363 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-364 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-365 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-366 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-367 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-368 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-386 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-421 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-567 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-585 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-663 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-820 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-821 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1058 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1088 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-255\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-255 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-256 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-257 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-260 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-261 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-262 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-263 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-324 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-521 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-523 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-549 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-620 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-640 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-798 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-916 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-310\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-332 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-310 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-261 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-324 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-325 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-328 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-331 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-334 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-335 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-338 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-347 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-916 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1240 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-320\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-320 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-321 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-323 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-324 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1214\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1214 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-346 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-347 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-348 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-349 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-351 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-353 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-354 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-494 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-565 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-649 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-829 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-924 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-19\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-19 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-130 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-166 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-167 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-168 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-178 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-182 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-186 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-229 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-233 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-237 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-241 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-409 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-471 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-472 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-601 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-611 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-624 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-625 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-776 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1024 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-137\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-78 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-137 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-76 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-78 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-79 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-88 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-89 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-90 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-91 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-93 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-94 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-96 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-117 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-140 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-170 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-188 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-462 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-463 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-464 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-641 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-643 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-652 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-791 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-795 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-838 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-917 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1236 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1225\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1225 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1053 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1068 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1110 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1111 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1112 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1118 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1219\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-426 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1219 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-23 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-36 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-41 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-59 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-66 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-378 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-379 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-426 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-427 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-428 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1227\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1227 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1054 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1057 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1062 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1083 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1090 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1100 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1105 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-389\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-389 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-209 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-248 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-252 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-253 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-390 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-391 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-392 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-393 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-394 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-395 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-396 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-397 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-544 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-584 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-600 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-617 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-756 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1069 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-569\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-569 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-480 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-570 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-571 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-588 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-595 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-783 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-429\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-429 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-430 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-431 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-432 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-433 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-434 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-479 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-199\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-215 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-199 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-201 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-204 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-205 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-208 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-209 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-212 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-213 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-214 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-215 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-312 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-319 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-359 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-497 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-524 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-532 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-540 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-921 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1230 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-452\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-452 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-226 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-454 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-455 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-459 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-460 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1051 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1052 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1188 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1215\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1215 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-112 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-129 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-179 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-183 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-184 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-606 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-641 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1173 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1216\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1216 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-645 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1218\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-119 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1218 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-120 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-123 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-124 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-125 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-131 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-786 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-787 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-788 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-805 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-189\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-190 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-189 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-128 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-190 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-191 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-192 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-193 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-197 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-198 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-369 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-681 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-839 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1077 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-275\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-275 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-276 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-277 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-278 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-279 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-280 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-281 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-618 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-766 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-767 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-465\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-415 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CWE-416 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CWE-467 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CWE-476 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-465 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-466 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-467 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-468 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-469 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-476 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-587 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-588 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-763 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-822 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-823 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-824 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-825 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-265\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-243 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-265 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-243 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-250 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-266 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-267 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-268 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-270 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-272 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-273 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-274 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-280 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-501 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-580 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-648 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1213\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1213 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-331 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-334 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-335 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-338 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-341 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-342 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-343 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1241 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-411\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-411 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-412 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-413 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-414 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-609 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-764 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-765 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-832 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-833 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-399\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-399 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-73 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-403 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-410 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-470 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-502 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-619 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-641 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-694 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-763 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-770 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-771 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-772 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-826 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-908 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-909 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-910 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-911 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-914 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-915 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-920 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1188 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-387\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-387 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-364 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-432 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-828 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-831 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-371\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-371 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-15 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-372 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-374 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-375 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1265 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-133\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CWE-134 Weakness Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-133 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-134 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-135 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-597 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-136\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-136 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-681 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-843 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-355\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-355 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-317 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-356 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-357 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-447 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-448 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-449 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-450 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-549 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1007 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-1021 Measure\" : { }\r\n"
        		+ "ENDLINE        }\r\n"
        		+ "ENDLINE      },\r\n"
        		+ "ENDLINE      \"Category CWE-1217\" : {\r\n"
        		+ "ENDLINE        \"description\" : \"\",\r\n"
        		+ "ENDLINE        \"eval_strategy\" : \"evaluator.WeightedAverageEvaluator\",\r\n"
        		+ "ENDLINE        \"children\" : {\r\n"
        		+ "ENDLINE          \"CVE-CWE-1217 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-488 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-613 Measure\" : { },\r\n"
        		+ "ENDLINE          \"CVE-CWE-841 Measure\" : { }";
        String[] arr = structure.split("ENDLINE");
		
        List<String> cweList = Arrays.asList(toolFindings);
        int i = 0;
		for (String line : arr) {
			if (line.contains("Measure") && line.contains("CVE")) {
				String cwe = line.trim().substring(5,12);
				if (!cweList.contains(cwe.trim())) {
					arr[i] = "";
				}
			}
			i++;
		}
		for (String line : arr) {
			System.out.println(line);
		}
	}
		

}
